# Generated by Django 5.0.4 on 2024-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='persons',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
