# Generated by Django 5.0.4 on 2024-04-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='preparing', max_length=20),
        ),
    ]
