# Generated by Django 5.0.4 on 2024-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chef_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='status',
            field=models.CharField(choices=[('approved', 'Preparing'), ('preparing', 'Ready'), ('completed', 'Delivered')], default='preparing', max_length=20),
        ),
    ]
