# Generated by Django 5.0.4 on 2024-04-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chef_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='status',
            field=models.CharField(choices=[('approved', 'Preparing'), ('preparing', 'Ready'), ('completed', 'Delivered')], default='approved', max_length=20),
        ),
    ]
