# Generated by Django 5.0.4 on 2024-04-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chef_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='status',
            field=models.CharField(choices=[('preparing', 'Approved'), ('ready', 'Preparing'), ('delivered', 'Completed')], default='preparing', max_length=20),
        ),
    ]
