# Generated by Django 5.0.4 on 2024-04-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_chef_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chef',
            new_name='Status',
        ),
    ]
